"""Evidence-led client results. Figures come from owner-supplied case studies."""
import html

CASES = [
 dict(slug='case-study-brigantine', place='Brigantine, New Jersey', title='A beach house with a clearer reason to book',
      desc='How guest positioning, listing improvements and pricing work came together for a four-bedroom beach house in Brigantine.',
      service='listing-optimization', service_name='Property & Listing Optimization', metric='0.09% to 0.53%', label='Reported overall conversion in the initial comparison',
      period='July 2025-January 2026 baseline vs. January 26-March 1, 2026. Different reporting windows; later results included below.',
      problem='A four-bedroom beach house near the shore had a strong physical offering, but its listing was not communicating a compelling reason to book beyond the summer season. The project connected ideal guest positioning, listing presentation and pricing strategy.',
      work=[('Guest intelligence','Developed an ideal guest profile and additional weekday and shoulder-season guest segments to guide the positioning.'),
            ('Listing copy and photo presentation','Reworked the title, description and supporting listing sections. Added descriptive captions, reviewed the photo sequence and enhanced lighting and presentation while keeping property details accurate.'),
            ('Pricing and channel strategy','Reviewed PriceLabs occupancy-based adjustments, seasonal profiles and pricing offsets between Airbnb and Vrbo. The work considered rate strategy alongside the message shown to guests.')],
      headers=['Reported metric','Baseline','Initial follow-up','Later follow-up'],
      rows=[['Overall conversion','0.09%','0.53%','0.10%'],['First-page search impression rate','53.1%','63.9%','65.5%'],['Search-to-listing conversion','8.28%','15.77%','4.62%'],['Listing-to-booking conversion','1.04%','3.33%','2.13%']],
      result='The initial comparison showed overall conversion rising by 0.44 percentage points, or approximately 489% relative to the rounded baseline. Search-to-listing and listing-to-booking conversion also increased. This was an observed early improvement, not a sustained sixfold result.',
      followup='The later dashboard, covering February 27-March 29, showed overall conversion at 0.10%, close to the original 0.09% baseline. Listing-to-booking conversion remained higher at 2.13% versus 1.04%, while search-to-listing conversion fell below the baseline. The follow-up demonstrates why each stage of the funnel should be monitored, rather than assuming the initial lift will persist.',
      evidence='Source: Airbnb dashboard screenshots reproduced in the supplied Brigantine case study. The listing was updated on January 30, 2026. The baseline spans July 2025-January 2026; the initial comparison covers January 26-March 1, including days before the update. The later window is February 27-March 29 and overlaps the initial window. These are unequal, partly overlapping periods, not a controlled experiment. Absolute traffic and booking counts were not supplied. Changes in demand, availability, pricing and guest mix may also affect conversion. The screenshots do not establish why Airbnb search placement changed.',
      takeaway='Guest targeting, presentation and pricing should work from a shared plan. Review the initial response, then keep checking the complete funnel as the booking season changes.'),
 dict(slug='case-study-north-carolina', place='North Carolina', title='A booking website and a broader route to guests',
      desc='A seven-unit tiny-home community recorded 13.3% higher rental revenue year over year after website and distribution improvements.',
      service='websites-funnels', service_name='Websites & Booking Funnels', metric='+13.3%', label='Reported rental revenue, January-May year over year',
      period='January 1-May 31, 2024 compared with January 1-May 31, 2025.',
      problem='A seven-unit tiny-home community had Hostaway in place, but its website sent visitors to Airbnb rather than supporting direct conversion. Its booking infrastructure and channel presentation were not making full use of the tools already available.',
      work=[('Direct booking infrastructure','Built a Hostaway-native booking website with clearer copy, calls to action and a direct booking journey. Connected the website to Google Vacation Rentals through Hostaway.'),
            ('Consistent listing presentation','Rewrote Airbnb and Vrbo listing content and improved photo order and presentation. The client supplied upgraded images.'),
            ('Broader distribution','Activated Hostaway Direct through Google Vacation Rentals in April 2024 and developed a more connected mix of direct and OTA booking channels.')],
      headers=['Reported metric','Jan-May 2024','Jan-May 2025','Change'],
      rows=[['Rental revenue','$50,362.80','$57,075.19','+$6,712.39 / +13.3%'],['Nights booked','391','458','+67 / +17.1%'],['Occupancy','36.75%','43.33%','+6.58 percentage points']],
      result='The January-May comparison recorded more rental revenue and booked nights in 2025. Occupancy increased by 6.58 percentage points, equivalent to approximately 17.9% relative growth. The project illustrates how website infrastructure, existing software and channel distribution can be improved together.',
      followup='The source also reports ADR declining from $126.37 to $119.26, approximately 5.6%, and average revenue per stay rising from $435.07 to $539.74, approximately 24.1%. These are reported measures with definitions still to be reconciled: the ADR values do not equal the rental revenue totals divided by booked nights. The results therefore should not be read as evidence that every performance measure improved.',
      evidence='Source: the supplied STR Booster North Carolina case study. Work began in early 2024, and the new direct distribution channel was activated in April 2024. The comparison uses the same calendar months in consecutive years, not the five months immediately after implementation. The 2024 period already includes some implementation activity. Underlying booking exports, direct-booking counts and channel shares were not supplied, so a claim that direct bookings tripled is not made here. Revenue definitions, available inventory and ADR require reconciliation. The comparison does not isolate the contribution of individual changes or establish net profit or commission savings.',
      takeaway='A direct booking website becomes more useful when it connects to distribution and the operating system behind the property. More bookings and more revenue can coexist with a lower reported nightly rate.'),
 dict(slug='case-study-tuscany', place='Tuscany, Italy', title='A well-reviewed stay with a stronger listing journey',
      desc='Guest-focused listing changes for a three-bedroom Tuscan property, with reported Airbnb funnel results and measurement context.',
      service='listing-optimization', service_name='Property & Listing Optimization', metric='8.74% to 12.04%', label='Reported search-to-listing conversion',
      period='March 14-April 14, 2026 compared with April 16-May 15, 2026. The stated date ranges are not equal in length.',
      problem='A three-bedroom stone home in a Tuscan hilltop village had Guest Favorite status and a reported 4.98 rating across 42 reviews. The project focused on making the listing presentation communicate the property’s character and relevance to its ideal guest.',
      work=[('Guest-focused copy','Rewrote the title, description and image captions around the travel needs and experiences the property could genuinely serve.'),
            ('Photo presentation','Improved the photo set and its sequence to make the stay easier to understand, from the search image through the rest of the listing.'),
            ('Listing completeness','Reviewed amenities and property information so guests could better assess the fit. The case does not rely on an unverified claim about how Airbnb’s algorithm uses individual fields.')],
      headers=['Reported metric','Before','After','Change'],
      rows=[['Overall conversion','0.12%','6.48%','+6.36 percentage points'],['First-page search impression rate','45.7%','44.4%','-1.3 percentage points'],['Search-to-listing conversion','8.74%','12.04%','+3.30 percentage points'],['Listing-to-booking conversion','1.33%','53.85%','+52.52 percentage points']],
      result='The reported figures show higher conversion at both the search-to-listing and listing-to-booking stages. Search-to-listing conversion increased approximately 37.8% relative to its starting rate. Overall conversion reached 54 times the rounded starting rate, but that ratio is not a measure of booking volume, revenue growth or future booking potential.',
      followup='First-page search impression share changed from 45.7% to 44.4%. A similar share does not mean total impressions or traffic volume stayed constant. The source reports the gap above similar listings widening from 0.01 to 6.24 percentage points; that comparison provides context but does not isolate the effect of the listing changes.',
      evidence='Source: Airbnb Performance figures transcribed in the supplied Tuscany case study. The stated periods are March 14-April 14 and April 16-May 15, 2026; these should not be described as equal 30-day windows. Absolute search impressions, listing views and bookings were not provided, and the exceptional 53.85% listing-to-booking figure needs that volume context. Later performance was not provided. Seasonal demand, availability and guest mix may contribute to the difference. The results are an observational comparison, not proof that listing edits alone caused the change. Property details are generalized in the source at the client’s request.',
      takeaway='Strong guest reviews do not remove the need for clear positioning. Evaluate both the search card and the listing page, and use booking counts alongside percentages when judging the response.'),
 dict(slug='case-study-phoenix', place='Phoenix, Arizona', title='Making an existing pricing tool work harder',
      desc='A two-bedroom Phoenix rental reported $965 more revenue across two 30-day periods following a PriceLabs configuration review.',
      service='revenue-management', service_name='Revenue Management & Distribution', metric='+$965', label='Reported revenue difference across two 30-day periods',
      period='Two 30-day reporting periods; exact calendar dates were not supplied.',
      problem='A two-bedroom rental with Superhost status was using PriceLabs with near-default settings. The project reviewed how its pricing rules responded to demand, booking activity and gaps in the calendar.',
      work=[('Price positioning','Reviewed the base price, reported as moving from $115 to $128, and the relationship between pricing and market demand.'),
            ('Demand-responsive settings','Reviewed seasonality, booking-recency adjustments and occupancy-based pricing rather than relying on outdated manual discounts.'),
            ('Stay rules and gaps','Revisited minimum stays and enabled one-night orphan-gap availability where appropriate. These settings were specific to this property, not universal recommendations.')],
      headers=['Reported metric','Before','After','Change'],
      rows=[['Total revenue','$2,159','$3,124','+$965 / +44.7%'],['Booked nights','17','22','+5 / +29.4%'],['Average daily rate','$127','$142','+$15 / +11.8%']],
      result='The supplied revenue totals show an increase of approximately 44.7%, correcting the original 43% revenue headline. Both booked nights and the reported average daily rate increased. The revenue totals reconcile with the reported nights multiplied by ADR in each period.',
      followup='The original report also lists occupancy moving from 58% to 74% and RevPAR from $73.66 to $105.08. Those occupancy figures do not align with 17 and 22 booked nights out of 30, so occupancy and RevPAR are not used as headline results here. Availability definitions and calendar dates need confirmation before those measures can be compared reliably.',
      evidence='Source: the supplied Phoenix PriceLabs optimization case study. Exact calendar dates, underlying platform exports and available-night definitions were not supplied. The published comparison uses the revenue, night and ADR figures that reconcile arithmetically within that report. It is not an independently audited or controlled comparison. Market demand, seasonality and other changes may have affected performance. No claim is made that these settings will produce the same outcome for another property.',
      takeaway='Connecting a pricing tool is the starting point. Its configuration should reflect the property, its calendar and its operating constraints, with performance reviewed after changes.')
]

def esc(s): return html.escape(s,quote=True)

def cards(items):
    return '<div class="grid two">'+''.join('<article class="card case-card"><p class="eyebrow">'+esc(c['place'])+'</p><h3>'+esc(c['title'])+'</h3><p class="case-metric">'+esc(c['metric'])+'</p><p>'+esc(c['label'])+'</p><p class="note">'+esc(c['period'])+'</p><a class="text-link" href="/'+c['slug']+'.html">Read the case study →</a></article>' for c in items)+'</div>'

def featured():
    return '<section class="section white" id="client-results"><div class="wrap"><div class="intro"><p class="eyebrow">Client results</p><h2>See the work.<br>Understand the results.</h2><p>Two different properties, connected improvements and the evidence behind each story.</p></div>'+cards(CASES[:2])+'<p class="note">Individual project results, with reporting periods and limitations explained in each case study. Outcomes vary.</p><div class="actions"><a class="btn secondary" href="/client-results.html">Explore All Case Studies</a></div></div></section>'

def render_cases(page,hero,section,cta):
    page('client-results','Vacation Rental Case Studies & Client Results','Explore STR Booster case studies in listing optimization, revenue management, direct booking websites and distribution.',hero('Client Results','Practical changes.<br><em>Results in context.</em>','Explore what changed, what was reported and what each comparison can tell us. Each case includes its reporting period and measurement limitations.')+section(cards(CASES),'white')+cta())
    for c in CASES:
        table='<div class="case-table-scroll" role="region" aria-label="Performance comparison" tabindex="0"><table class="case-table"><caption>'+esc(c['period'])+'</caption><thead><tr>'+''.join('<th scope="col">'+esc(v)+'</th>' for v in c['headers'])+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">'+esc(v)+'</th>') if i==0 else '<td>'+esc(v)+'</td>' for i,v in enumerate(row))+'</tr>' for row in c['rows'])+'</tbody></table></div>'
        work='<h2>What changed</h2>'+''.join('<h3>'+esc(t)+'</h3><p>'+esc(p)+'</p>' for t,p in c['work'])
        prose='<article class="case-prose"><p class="eyebrow">'+esc(c['place'])+'</p><h2>The starting point</h2><p>'+esc(c['problem'])+'</p>'+work+'<h2>Reported performance</h2>'+table+'<p>'+esc(c['result'])+'</p><h2>What the comparison also shows</h2><p>'+esc(c['followup'])+'</p><aside class="case-evidence"><h2>Evidence and measurement context</h2><p>'+esc(c['evidence'])+'</p></aside><h2>The practical lesson</h2><p>'+esc(c['takeaway'])+'</p><p class="note">Prepared by STR Booster from the supplied project case study. Individual results are not a forecast or guarantee.</p><div class="actions"><a class="btn" href="/'+c['service']+'.html">'+esc(c['service_name'])+'</a><a class="btn secondary" href="/get-expert-help.html?service='+c['service']+'">Discuss Your Property</a></div><p class="case-back"><a href="/client-results.html">← All client results</a></p></article>'
        page(c['slug'],c['title'],c['desc'],hero('Client Case Study',c['title'],c['desc'])+section(prose,'white'))
